### ISSUE TITLE
npm i doesn't work

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi-filters#187]
Tried on a clean checkout with both node 10 and node 6.

When building from the commit at the start of the year, it works fine, so it's https://github.com/pixijs/pixi-filters/pull/181 that's causing the problems.

On Windows 7

```
lerna ERR! npm install stderr:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.3.1/canvas-v2.3.1-node-v64-win32-unknown-x64.ta
.gz
node-pre-gyp WARN Pre-built binaries not found for canvas@2.3.1 and node@10.15.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Projects\WebGL_ThirdParty\pixi-filters\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Projects\\WebGL_ThirdParty\\pixi-filters\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fall
ack-to-build" "--module=C:\\Projects\\WebGL_ThirdParty\\pixi-filters\\node_modules\\canvas\\build\\Release\\canvas.node" "--module_name=canvas" "--module_path=
:\\Projects\\WebGL_ThirdParty\\pixi-filters\\node_modules\\canvas\\build\\Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_n
pi_label=node-v64"
gyp ERR! cwd C:\Projects\WebGL_ThirdParty\pixi-filters\node_modules\canvas
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Projects\WebGL_ThirdParty\pixi-filters\node_modules\node-gyp\bin\node-gyp
js build --fallback-to-build --module=C:\Projects\WebGL_ThirdParty\pixi-filters\node_modules\canvas\build\Release\canvas.node --module_name=canvas --module_pat
=C:\Projects\WebGL_ThirdParty\pixi-filters\node_modules\canvas\build\Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=nod
-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Projects\WebGL_ThirdParty\pixi-filters\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Windows_NT 6.1.7601
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Projects\\WebGL_ThirdParty\\pixi-filters\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "
nstall" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Projects\WebGL_ThirdParty\pixi-filters\node_modules\canvas
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.3.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.3.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dave.moore\AppData\Roaming\npm-cache\_logs\2019-01-22T09_47_19_778Z-debug.log

lerna ERR! npm install exited 1 in 'pixi-filters'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ bootstrap: `lerna bootstrap --hoist --no-ci`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dave.moore\AppData\Roaming\npm-cache\_logs\2019-01-22T09_47_19_888Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the undefined postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\dave.moore\AppData\Roaming\npm-cache\_logs\2019-01-22T09_47_19_938Z-debug.log
```

**Comment by bigtimebuddy** [comment]
Looks like node-pre-gyp trying to download code and failing on Windows. This isn’t a direct dependency, so we might need to update dependencies. Try npm update then reinstall to see if any fix was introduced. If not...

Could you do a quick search for this on GitHub and see if there are any recent issues? If not, I’ll try to look at it later this week.

**Comment by themoonrat** [comment]
Come to check out the repo again for upgrading to pixi 5, and everything worked fine :)
