### ISSUE TITLE
the new version is very hard to build.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#199]
node-canvas is very hard to install.
it needs many native dependencies lib.
and some of them can't install easily.

I've spend many hours to install it and I failed.

I meet different error randomly , e.g. : 
```
> canvas@2.4.1 install /Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas
> node-pre-gyp install --fallback-to-build

Failed to execute '/Users/rocky/.nvm/versions/node/v10.15.1/bin/node /Users/rocky/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)

lerna ERR! npm install stderr:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.4.1 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ETIMEDOUT 13.229.188.59:443
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'pangocairo' found
gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/rocky/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/rocky/.nvm/versions/node/v10.15.1/bin/node" "/Users/rocky/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/Users/rocky/.nvm/versions/node/v10.15.1/bin/node /Users/rocky/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:970:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command "/Users/rocky/.nvm/versions/node/v10.15.1/bin/node" "/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas
node-pre-gyp ERR! node -v v10.15.1
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@2.4.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@2.4.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

or 

```
lerna ERR! npm install stderr:
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for canvas@2.4.1 and node@10.15.1 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error connect ETIMEDOUT 13.229.188.59:443
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
gyp: Call to 'pkg-config cairo --cflags-only-I | sed s/-I//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/rocky/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "/Users/rocky/.nvm/versions/node/v10.15.1/bin/node" "/Users/rocky/.nvm/versions/node/v10.15.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas/build/Release" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /Users/rocky/DEV/@git-finscn/my-pixi/pixi-filters/node_modules/canvas
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
```
or something else.

---------

In fact , I've  already installed  
 pkg-config 
cairo 
pango
 libpng
 jpeg 
giflib
 libffi

with
```
brew reinstall pkg-config cairo pango libpng jpeg giflib libffi
```

**Comment by finscn** [comment]
You search on stackoverflow ,github, google , I can find many people ask "How to install node-canvas" ,  "Can't install node-anvas" ...

Many years ago , I've tried use node-canvas in my project. 
I wasted many time to install & build it , Finally I abandoned.

I hate node-canvas

**Comment by bigtimebuddy** [comment]
This is a node-canvas issue not a pixi-filters issue. Closing.
