### ISSUE TITLE
Fails to build on old node version

### ISSUE THREAD

**Issue by themoonrat** [pixijs/pixi-filters#2]
I'm almost certain this is because of the old node I'm running (and which the company mandates... grrrrrr) - but there's an error when it tries to run the linting part. Could the script either fail to run if it detects an older node version, and / or provide pre-built bin files for those who may be in a similar situation please? Cheers

```
C:\Projects\WebGL\pixi-filters>npm run lint

> pixi-filters@1.0.0 lint C:\Projects\WebGL\pixi-filters
> eslint src/**/*.js

C:\Projects\WebGL\pixi-filters\node_modules\eslint\node_modules\strip-bom\index.js:2
module.exports = x => {
                   ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Projects\WebGL\pixi-filters\node_modules\eslint\lib\config\config-file.js:23:16)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "lint"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! pixi-filters@1.0.0 lint: `eslint src/**/*.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pixi-filters@1.0.0 lint script 'eslint src/**/*.js'.
npm ERR! This is most likely a problem with the pixi-filters package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     eslint src/**/*.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls pixi-filters
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\WebGL\pixi-filters\npm-debug.log

C:\Projects\WebGL\pixi-filters>
```

**Comment by bigtimebuddy** [comment]
Looks like it's getting hung up on the fat arrow which are only in Node 4+, I believe.

**Comment by bigtimebuddy** [comment]
Possibly could use jshint instead of eslint, might fix this.

**Comment by bigtimebuddy** [comment]
Sorry, but we won't be updating build process to support Node < 4.
