### ISSUE TITLE
`npm run build` can't run.

### ISSUE THREAD

**Issue by finscn** [pixijs/pixi-filters#45]
I've install all node_modules .
but there're  some errors: 
```
rocky@Rocky-MBP pixi-filters [* master]$ npm run build

> @ prebuild /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters
> npm run lint


> @ lint /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters
> eslint scripts **/src **/rollup.config.js --fix


> @ build /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters
> lerna run build

lerna info version 2.4.0
lerna ERR! build Errored while running script in '@pixi/filter-ascii'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run build
lerna ERR! [!] Error: Cannot find module '@tools/build'
lerna ERR! Error: Cannot find module '@tools/build'
lerna ERR!     at Function.Module._resolveFilename (module.js:469:15)
lerna ERR!     at Function.Module._load (module.js:417:25)
lerna ERR!     at Module.require (module.js:497:17)
lerna ERR!     at require (internal/module.js:20:19)
lerna ERR!     at Object.<anonymous> (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii/rollup.config.js:5:29)
lerna ERR!     at Module._compile (module.js:570:32)
lerna ERR!     at Object.require.extensions..js (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/node_modules/rollup/bin/rollup:2675:8)
lerna ERR!     at Module.load (module.js:487:32)
lerna ERR!     at tryModuleLoad (module.js:446:12)
lerna ERR!     at Function.Module._load (module.js:438:3)
lerna ERR! 
lerna ERR! 
lerna ERR! npm ERR! Darwin 17.0.0
lerna ERR! npm ERR! argv "/Users/rocky/.nvm/versions/node/v6.10.3/bin/node" "/Users/rocky/.nvm/versions/node/v6.10.3/bin/npm" "run" "build:umd"
lerna ERR! npm ERR! node v6.10.3
lerna ERR! npm ERR! npm  v3.10.10
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! @pixi/filter-ascii@2.0.2 build:umd: `rollup -c -f umd && rollup -cp -f umd`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the @pixi/filter-ascii@2.0.2 build:umd script 'rollup -c -f umd && rollup -cp -f umd'.
lerna ERR! npm ERR! Make sure you have the latest version of node.js and npm installed.
lerna ERR! npm ERR! If you do, this is most likely a problem with the @pixi/filter-ascii package,
lerna ERR! npm ERR! not with npm itself.
lerna ERR! npm ERR! Tell the author that this fails on your system:
lerna ERR! npm ERR!     rollup -c -f umd && rollup -cp -f umd
lerna ERR! npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! npm ERR!     npm bugs @pixi/filter-ascii
lerna ERR! npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! npm ERR!     npm owner ls @pixi/filter-ascii
lerna ERR! npm ERR! There is likely additional logging output above.
lerna ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR! 
lerna ERR! npm ERR! Please include the following file with any support request:
lerna ERR! npm ERR!     /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii/npm-debug.log
lerna ERR! 
lerna ERR! npm ERR! Darwin 17.0.0
lerna ERR! npm ERR! argv "/Users/rocky/.nvm/versions/node/v6.10.3/bin/node" "/Users/rocky/.nvm/versions/node/v6.10.3/bin/npm" "run" "build"
lerna ERR! npm ERR! node v6.10.3
lerna ERR! npm ERR! npm  v3.10.10
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! @pixi/filter-ascii@2.0.2 build: `npm run build:umd && npm run build:es`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR! 
lerna ERR! npm ERR! Failed at the @pixi/filter-ascii@2.0.2 build script 'npm run build:umd && npm run build:es'.
lerna ERR! npm ERR! Make sure you have the latest version of node.js and npm installed.
lerna ERR! npm ERR! If you do, this is most likely a problem with the @pixi/filter-ascii package,
lerna ERR! npm ERR! not with npm itself.
lerna ERR! npm ERR! Tell the author that this fails on your system:
lerna ERR! npm ERR!     npm run build:umd && npm run build:es
lerna ERR! npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! npm ERR!     npm bugs @pixi/filter-ascii
lerna ERR! npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! npm ERR!     npm owner ls @pixi/filter-ascii
lerna ERR! npm ERR! There is likely additional logging output above.
lerna ERR! npm WARN Local package.json exists, but node_modules missing, did you mean to install?
lerna ERR! 
lerna ERR! npm ERR! Please include the following file with any support request:
lerna ERR! npm ERR!     /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii/npm-debug.log
lerna ERR! 
lerna ERR! > @pixi/filter-ascii@2.0.2 build /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii
lerna ERR! > npm run build:umd && npm run build:es
lerna ERR! 
lerna ERR! 
lerna ERR! > @pixi/filter-ascii@2.0.2 build:umd /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii
lerna ERR! > rollup -c -f umd && rollup -cp -f umd
lerna ERR! 
lerna ERR! 
lerna ERR!     at Promise.all.then.arr (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/node_modules/execa/index.js:236:11)
lerna WARN complete Waiting for 3 child processes to exit. CTRL-C to exit immediately.
lerna ERR! build Errored while running script in '@pixi/filter-color-replace'
lerna ERR! build Errored while running script in '@pixi/filter-bloom'
lerna ERR! build Errored while running script in '@pixi/filter-bulge-pinch'
(node:19430) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error: Command failed: npm run build
[!] Error: Cannot find module '@tools/build'
Error: Cannot find module '@tools/build'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii/rollup.config.js:5:29)
    at Module._compile (module.js:570:32)
    at Object.require.extensions..js (/Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/node_modules/rollup/bin/rollup:2675:8)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)


npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/rocky/.nvm/versions/node/v6.10.3/bin/node" "/Users/rocky/.nvm/versions/node/v6.10.3/bin/npm" "run" "build:umd"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @pixi/filter-ascii@2.0.2 build:umd: `rollup -c -f umd && rollup -cp -f umd`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pixi/filter-ascii@2.0.2 build:umd script 'rollup -c -f umd && rollup -cp -f umd'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @pixi/filter-ascii package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup -c -f umd && rollup -cp -f umd
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @pixi/filter-ascii
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @pixi/filter-ascii
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii/npm-debug.log

npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/rocky/.nvm/versions/node/v6.10.3/bin/node" "/Users/rocky/.nvm/versions/node/v6.10.3/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @pixi/filter-ascii@2.0.2 build: `npm run build:umd && npm run build:es`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pixi/filter-ascii@2.0.2 build script 'npm run build:umd && npm run build:es'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @pixi/filter-ascii package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:umd && npm run build:es
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @pixi/filter-ascii
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @pixi/filter-ascii
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii/npm-debug.log

> @pixi/filter-ascii@2.0.2 build /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii
> npm run build:umd && npm run build:es


> @pixi/filter-ascii@2.0.2 build:umd /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/filters/ascii
> rollup -c -f umd && rollup -cp -f umd



npm ERR! Darwin 17.0.0
npm ERR! argv "/Users/rocky/.nvm/versions/node/v6.10.3/bin/node" "/Users/rocky/.nvm/versions/node/v6.10.3/bin/npm" "run" "build"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @ build: `lerna run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script 'lerna run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     lerna run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/rocky/DEV/@git-fav/_pixijs.com/pixi-filters/npm-debug.log
rocky@Rocky-MBP pixi-filters [* master]$ 


```

**Comment by bigtimebuddy** [comment]
Please read this: 
https://github.com/pixijs/pixi-filters#building

You need to run `npm run bootstrap`
